name: MSBuild

on:
  push:
    branches: [ "main", "answer" ]
  pull_request:
    branches: [ "main", "answer" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup project
      run: ${{github.workspace}}/Setup.bat

    - name: Build Debug x64
      run: msbuild ${{github.workspace}}/Frame.sln /p:Configuration=Debug /p:Platform=x64

    - name: Build Release x64
      run: msbuild ${{github.workspace}}/Frame.sln /p:Configuration=Release /p:Platform=x64
